---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/engine"
    schedule:
      interval: "daily"
  - package-ecosystem: npm
    directory: "/client"
    schedule:
      interval: "daily"
